import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboardSideDrawer from "@/components/DashboardSideDrawer";
import ThemeContextProvider from "@/context/theme-context";
import ThemeSwitch from "@/components/theme-switch";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="w-full flex flex-col lg:flex-row h-full overflow-y-auto">
            <div className="absolute z-50">
              <DashboardSideDrawer />
            </div>
            <div className=" flex-1 relative h-dvh w-dvw">{children}</div>
          </div>
          <ThemeSwitch />
        </ThemeProvider>
      </body>
    </html>
  );
}
